### ISSUE TITLE
Are the Serializer.Serialize/Deserialize methods thread-safe?

### ISSUE THREAD

**Issue by ArcticEcho** [skbkontur/GroBuf#13]
Given a single instance of the `Serializer` class, do I need to follow the standard `lock (...) { ... }` approach if I have multiple threads invoking the class's `Serialize` and `Deserialize` methods?

**Comment by AndrewKostousov** [comment]
No, you don't need any locks around `Serializer` instances. `Serialize` and `Deserialize` methods are thread safe.

**Comment by ArcticEcho** [comment]
Excellent, thanks for the quick reply!
