### ISSUE TITLE
Memory leak when more instatnces created

### ISSUE THREAD

**Issue by Bicik** [skbkontur/GroBuf#29]
Hello,
I'd like to use GroBuf serializer as one of the "sinks" in our remoting client-server communication because of its high performance compare to standard BinaryFormatter. We have a single call type of communication (new instance of server-side class for each client call) so there are a lot of instances of serializer created. The Serializer class doesn't implement IDisposable interface and cause memory leak. 

Is there any way, how to destroy the serializer? Is it possible to implement IDisposable interface? Use static instance of the serializer is not possible for us because of the perfomance degrade.

Thank you a lot V.

**Comment by Bicik** [comment]
Hello,
on the server side I used it this way:

 `public override byte[] GetListBin(Guid threadId)
        {
            var tmpResult = GetList(threadId);

            if (tmpResult == null || tmpResult.Count == 0)
                return null;

            var serializer = new Serializer(new PropertiesExtractor(), options: GroBufOptions.WriteEmptyObjects);

            return serializer.Serialize(tmpResult);
        }` 
Type of input parameter "tmpResult" is List<object[]>, where object[] is the result of DbDataReader.GetValues(). So types of these objects are only basic types returned from database. I think, that is the reason, why I've not found any performance issue when creating new instance of the serializer.

The problem with using GroBuf as singleton on the server side is simply creating a bottleneck. We have to serve a lot of clients at the time (1000+) and they download MBs of data (from 10s to 100s MBs). I didn´t find info, that the serializer is thread safe, so I suppose use it like this:

`...
private static Serializer serializer = new Serializer(new PropertiesExtractor(), options: GroBufOptions.WriteEmptyObjects);
private static object serializerLock = new object();
...
public override byte[] GetListBin(Guid threadId)
        {
            var tmpResult = GetList(threadId);

            if (tmpResult == null || tmpResult.Count == 0)
                return null;
           lock(serializerLock)
           {
                 return serializer.Serialize(tmpResult);
           }
        }`

**Comment by Anton92nd** [comment]
Yes, GroBuf is thread-safe, you don't have to put it inside a `lock` section. It doesn't have any state, that can be corrupted by multithreaded access. As for the generated code cache I mentioned earlier, it is always accessed in a thread-safe manner (via `lock` sections), and methods stored in the cache are also thread-safe, so you can serialize multiple instances of the same type concurrently.

**Comment by Anton92nd** [comment]
We use GroBuf like this in heavily-loaded applications for severals years and we haven't encountered any issues concerning concurrent serialization/deserialization.
I think I should add a note about thread-safety somewhere in the README file.
